.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NUSPELL" "1" "September 2018" "" ""
.
.SH "NAME"
\fBnuspell\fR \- spell checker
.
.SH "SYNOPSIS"
\fBnuspell\fR [\-d \fIdict_NAME\fR] [\-i \fIENCODING\fR] [\fIFILE\fR]\.\.\.
.
.br
\fBnuspell\fR \-l|\-G [\-L] [\-d \fIdict_NAME\fR] [\-i \fIENCODING\fR] [\fIFILE\fR]\.\.\.
.
.br
\fBnuspell\fR \-D|\-h|\-\-help|\-v|\-\-version
.
.SH "DESCRIPTION"
Nuspell checks spelling of each \fIFILE\fR\. Without \fIFILE\fR, checks standard input\.
.
.SH "OPTIONS"
.
.TP
\fB\-d\fR \fIdi_CT\fR
use \fIdi_CT\fR dictionary\. Only one dictionary is currently supported\.
.
.TP
\fB\-D\fR
print search paths and available dictionaries and exit
.
.TP
\fB\-i\fR \fIENCODING\fR
input/output encoding, default is active locale
.
.TP
\fB\-l\fR
print only misspelled words or lines
.
.TP
\fB\-G\fR
print only correct words or lines
.
.TP
\fB\-L\fR
lines mode
.
.TP
\fB\-S\fR
use Unicode text segmentation to extract words
.
.TP
\fB\-U\fR
do not suggest, increases performance
.
.TP
\fB\-h, \-\-help\fR
display this help and exit
.
.TP
\fB\-v, \-\-version\fR
print version number and exit
.
.SH "ENVIRONMENT"
.
.TP
DICPATH
Dictionary path\.
.
.SH "RETURN VALUES"
Returns error if the argument syntax is invalid or some file can not be opened\. Otherwise, spell checking has occured and returns success\.
.
.SH "BUGS"
Bug reports: \fIhttps://github\.com/nuspell/nuspell/issues\fR
.
.SH "EXAMPLES"
.
.nf

nuspell \-d en_US file\.txt
.
.fi
.
.SH "AUTHOR"
.
.SH "COPYRIGHT"
.
.SH "SEE ALSO"
Full documentation: \fIhttps://github\.com/nuspell/nuspell/wiki\fR
.
.P
Home page: \fIhttp://nuspell\.github\.io/\fR
